server:
  port: 8081
  servlet:
    context-path: /consumer

spring:
  application:
  name: sqs-demo-consumer

application:
  sqs-uri: http://localhost:4566 #  https://localhost.localstack.cloud:4566/000000000000/doc-sent #
  sqs-region: sa-east-1
  sqs-queue-name: doc-sent
  external-uri: http://localhost:8082/receiver